"""Generates nfc_latin.go: the canonical compositions (base + combining mark -> precomposed) for
Latin letters, from Python's unicodedata. Covers U+00C0-U+024F and U+1E00-U+1EFF, whose NFD is a
base letter followed by marks in U+0300-U+036F. Run: python3 testdata/gen_nfc_latin.py > nfc_latin.go
"""
import unicodedata, sys
pairs = []
for cp in list(range(0xC0, 0x250)) + list(range(0x1E00, 0x1F00)):
    ch = chr(cp)
    d = unicodedata.decomposition(ch)
    if not d or d.startswith('<'):
        continue
    parts = [int(x, 16) for x in d.split()]
    if len(parts) != 2 or not (0x300 <= parts[1] <= 0x36F):
        continue
    if unicodedata.normalize('NFC', chr(parts[0]) + chr(parts[1])) != ch:
        continue
    pairs.append((parts[0], parts[1], cp))
pairs.sort()
print("// Code generated by testdata/gen_nfc_latin.py; DO NOT EDIT.\n")
print("package tokenizer\n")
print("// nfcLatin lists canonical compositions base+mark -> precomposed for Latin letters, sorted by")
print("// (base, mark). Applied repeatedly, it composes stacked marks (e.g. U+1EA4 from A + U+0302 + U+0301).")
print("var nfcLatin = [...][3]rune{")
for b, m, c in pairs:
    print(f"\t{{0x{b:04X}, 0x{m:04X}, 0x{c:04X}}}, // {chr(c)}")
print("}")
